version: "3.8"
services:
  nagios-json:
    build: ./nagios-json
    ports:
    - "2000:80"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-container"
    ports:
      - "8082:8080"
    volumes:
      - ./swagger.json:/swagger/swagger.json
    environment:
      SWAGGER_JSON: /swagger/swagger.json
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    # uncomment following lines to access db locally
    # ports:
    #   - 27017:27017
    networks: 
     - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
