version: "3.8"
services:
  web:
    build: ./frontend
    depends_on:
      - api
    networks:
      - network-backend
  api:
    build: ./backend
    depends_on:
      - mongo
    networks: 
     - network-backend
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Mapeia a porta 6379 do contêiner para a porta 6379 do host
    networks: 
     - network-backend
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
      - api
    networks:
      - network-backend

  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    # uncomment following lines to access db locally
    # ports:
    #   - 27017:27017
    networks: 
     - network-backend

networks:
  network-backend:
    name: network-backend  # Nome explícito da rede

volumes: 
  mongodb_data:
